# Code Stats Configuration File
# This file controls how the code-stats tool analyzes your repository

# Language Detection
# Maps file extensions to language names for statistics
extensions:
  # Web Development
  js: JavaScript
  jsx: JavaScript
  ts: TypeScript
  tsx: TypeScript
  html: HTML
  css: CSS
  scss: SCSS
  vue: Vue
  svelte: Svelte

  # Backend Languages
  java: Java
  py: Python
  rb: Ruby
  php: PHP
  go: Go
  rs: Rust
  cpp: C++
  c: C
  cs: "C#"
  kt: Kotlin
  scala: Scala

  # Scripting & Shell
  sh: Shell
  bash: Bash
  ps1: PowerShell

  # Data & Config
  sql: SQL
  json: JSON
  yaml: YAML
  yml: YAML
  xml: XML
  toml: TOML
  md: Markdown
  markdown: Markdown

  # Mobile
  swift: Swift
  dart: Dart

  # Add your custom extensions here:
  # myext: "My Language"

# Language Detection for Files Without Extensions
# Maps specific filenames to language names
filenames:
  # DevOps and Build Files
  dockerfile: Docker
  makefile: Makefile
  jenkinsfile: Jenkins
  vagrantfile: Vagrant

  # Ruby ecosystem files
  rakefile: Ruby
  gemfile: Ruby
  podfile: Ruby
  fastfile: Ruby
  brewfile: Ruby

  # Add your custom filenames here:
  # myfile: "My Language"

# Directory Classification
# Files in these directories count as "production" code
productionDirectories:
  - src
  - lib
  - app
  - source
  - main
  # Add your production directories here

# Files in these directories count as "test" code
testDirectories:
  - test
  - tests
  - __tests__
  - spec
  - specs
  - cypress
  - e2e
  # Add your test directories here

# Email Aliases
# Group multiple emails/names to the same contributor
# Format: canonical_email -> list of aliases
aliases:
  # Example: if "john.doe@company.com" is the canonical identity:
  # "john.doe@company.com":
  #   - "john@personal.com"
  #   - "j.doe@company.com"
  #   - "John Doe <john.doe@company.com>"

  # Add your email aliases here
