---
name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Pass the NVD API key to Maven (masked by GitHub Actions)
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          # Caches ~/.m2 automatically
          cache: "maven"

      # Cache the OWASP Dependency-Check local DB so it doesn't fully re-download each run
      - name: Cache Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-dcdb-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dcdb-

      - name: Run build with quality checks
        run: ./mvnw clean verify -B -DnvdApiKey="${NVD_API_KEY}"

      - name: Build final JAR
        run: ./mvnw package -B -DskipTests

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            target/code-stats-1.0.0.jar
            target/dependency-check-report.html
            target/spotbugs.xml
            target/surefire-reports/
          retention-days: 7

  native-build:
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass
    if: github.ref == 'refs/heads/main'  # Only on main branch
    env:
      MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17"
          distribution: "graalvm-community"
          components: "native-image"
          cache: "maven"

      - name: Build native executable
        run: ./mvnw clean package -Pnative -B -DskipTests

      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: native-executable-linux
          path: target/code-stats
          retention-days: 30