---
name: "CI"
"on":
  push:
    branches:
    - "main"
    - "develop"
  pull_request:
    branches:
    - "main"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v4"
    - name: "Set up JDK 17"
      uses: "actions/setup-java@v4"
      with:
        java-version: "17"
        distribution: "temurin"
    - name: "Cache Maven packages"
      uses: "actions/cache@v4"
      with:
        path: "~/.m2"
        key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
        restore-keys: "${{ runner.os }}-m2"
    - name: "Run tests"
      run: "./mvnw clean test -B"
    - name: "Run security analysis"
      run: "./mvnw spotbugs:check -B\n./mvnw dependency-check:check -B\n"
    - name: "Run code formatting check"
      run: "./mvnw spotless:check -B"
    - name: "Build JAR"
      run: "./mvnw package -B -DskipTests"
    - name: "Upload build artifacts"
      uses: "actions/upload-artifact@v4"
      if: "always()"
      with:
        name: "build-reports"
        path: "target/code-stats-1.0.0.jar\ntarget/dependency-check-report.html\n\
          target/spotbugs.xml\ntarget/surefire-reports/\n"
        retention-days: 7
